using Generator.Database.Analyzers;
using Generator.Database.Extensions;
using Generator.Database.Models;
using System.Text;

namespace Generator.Database.Generators
{
    public static class CSharpProcedureGenerator
    {
        private const string ProcedureSourceTemplate = @"// <auto-generated />
// This file was automatically generated. Do not edit manually.

using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

using PlayGround.Database.Repositories;
using {DATABASE_NAME}.Tables;

namespace {DATABASE_NAME}.Procedures
{
    public class {PROCEDURE_NAME}({REPOSITORY_NAME} repository)
        : ProcedureBase(repository)
    {
{PARAMETER_PROPERTIES}
        public override string ProcedureName { get { return ""{PROCEDURE_SCHEMA}.{PROCEDURE_NAME}""; } }

        public override DynamicParameters BuildParameters()
        {
{SET_PARAMETER_INTERFACE}
            return Parameters;
        }

        //.// Return Value Interface
{HAS_RETURNVAL}
{GET_RETURNVAL_INTERFACE}
        //.// Result Class
{RESULT_CLASS}
    }
}";

        private const string ProcedureNoParamTemplate = @"// <auto-generated />
// This file was automatically generated. Do not edit manually.

using Dapper;
using System.Data;

using GrayDotNetCoreLib.GrayService;
using TpGeneratedCodes.Databases;
namespace TpGeneratedCodes.Database.{DATABASE_NAME};

public class {PROCEDURE_NAME}(GrayDatabaseService dbService) : {DATABASE_NAME}Procedure(dbService);";

        public static GeneratedFile Generate(string database, string databaseFullName, ProcedureSchema procedure)
        {
            var context = new GenerationContext();

            // 매개변수 처리
            foreach (var parameter in procedure.Parameters)
            {
                if (string.IsNullOrEmpty(parameter.DataType))
                {
                    continue;
                }

                ProcessParameter(parameter, context);
            }

            // 반환값 처리
            if (procedure.HasReturn)
            {
                ProcessReturnValue(context);
            }

            // Result 클래스 처리
            if (procedure.ResultColumns != null && procedure.ResultColumns.Count > 0)
            {
                ProcessResultClass(procedure.ResultColumns, context);
            }

            // 템플릿 교체
            var generated = BuildFinalCode(procedure.Schema, procedure.ProcedureName, databaseFullName, database, context);
            return new GeneratedFile
            {
                FileName = $"{procedure.ProcedureName}.cs",
                Content = generated,
                CodeType = CodeType.StoredProcedure,
                Database = databaseFullName
            };
        }

        private static void ProcessParameter(ParameterSchema parameter, GenerationContext context)
        {
            var paramName = parameter.ParameterName.TrimStart('@');
            var propertyName = paramName.ToFirstUpper();
            var (csharpType, valueType) = CSharpTypeConverter.GetCSharpType(parameter.DataType, parameter.DefinedType);

            // 속성 생성
            var defaultValue = CSharpTypeConverter.GetDefaultValue(valueType);
            context.ParameterProperties.Tab(2).AppendLine($"public {csharpType} {propertyName} {{ get; set; }} = {defaultValue};");

            // 매개변수 설정 생성
            if (context.SetParameters.Length > 0)
            {
                context.SetParameters.AppendLine();
            }

            var isOutParam = string.Equals("INOUT", parameter.ParameterMode, StringComparison.OrdinalIgnoreCase);
            if (isOutParam)
            {
                context.SetParameters.Tab(3).Append(
                    $@"Parameters.Add(""{paramName}"", {propertyName}, direction: ParameterDirection.Output, size: {parameter.CharacterMaximumLength});"
                );
            }
            else
            {
                context.SetParameters.Tab(3).Append($@"Parameters.Add(""{paramName}"", {propertyName});");
            }
        }

        private static void ProcessReturnValue(GenerationContext context)
        {
            // 반환값 속성 추가
            context.ParameterProperties.Tab(2).AppendLine($"public int ReturnValue {{ get; set; }} = 0;");

            // 반환값 매개변수 추가
            if (context.SetParameters.Length > 0)
            {
                context.SetParameters.AppendLine();
            }
            context.SetParameters.Tab(3).Append(@"Parameters.Add(""Return"", ReturnValue, direction: ParameterDirection.ReturnValue);");

            // 반환값 인터페이스 생성
            context.GetReturnValue.Clear();
            context.HasReturnValue.AppendLine();
            context.GetReturnValue.Tab(2).AppendLine(@"public override int GetReturnValue()");
            context.GetReturnValue.Tab(2).AppendLine(@"{");
            context.GetReturnValue.Tab(3).AppendLine(@"return Parameters.Get<int>(""Return"");");
            context.GetReturnValue.Tab(2).AppendLine(@"}");

            context.HasReturnValue.Clear();
            context.HasReturnValue.AppendLine();
            context.HasReturnValue.Tab(2).AppendLine(@"public override bool HasReturnValue()");
            context.HasReturnValue.Tab(2).AppendLine(@"{");
            context.HasReturnValue.Tab(3).AppendLine(@"return true;");
            context.HasReturnValue.Tab(2).AppendLine(@"}");
        }

        private static void ProcessResultClass(List<ResultColumnSchema> resultColumns, GenerationContext context)
        {
            if (resultColumns.Count == 0)
            {
                return;
            }

            context.ResultClass.AppendLine();

            // 단일 테이블에서 온 결과인지 확인
            var sourceTableName = resultColumns.FirstOrDefault()?.SourceTableName;
            var isFromSingleTable = !string.IsNullOrEmpty(sourceTableName) && resultColumns.All(c => c.SourceTableName == sourceTableName);
            if (isFromSingleTable)
            {
                // 기존 Table 클래스를 재사용
                context.ResultClass.Tab(2).AppendLine($"// Result is mapped to existing {sourceTableName}Entity class");
                context.ResultClass.Tab(2).AppendLine($"public {sourceTableName}Entity Result {{ get; set; }}");
            }
            else
            {
                // 커스텀 Result 클래스 생성
                context.ResultClass.Tab(2).AppendLine("public class ResultEntity");
                context.ResultClass.Tab(2).AppendLine("{");
                foreach (var column in resultColumns)
                {
                    var (csharpType, valueType) = CSharpTypeConverter.GetCSharpType(column.DataType, null);
                    // nullable 처리
                    if (column.IsNullable && valueType != CSharpTypeConverter.ValueType.String)
                    {
                        csharpType = csharpType + "?";
                    }

                    var defaultValue = column.IsNullable && valueType != CSharpTypeConverter.ValueType.String
                        ? "null"
                        : CSharpTypeConverter.GetDefaultValue(valueType);

                    context.ResultClass.Tab(3).AppendLine($"public {csharpType} {column.ColumnName} {{ get; set; }} = {defaultValue};");
                }

                context.ResultClass.Tab(2).AppendLine("}");
                context.ResultClass.Tab(2).AppendLine("");
                context.ResultClass.Tab(2).Append($"public ResultEntity Result {{ get; set; }}");
            }
        }

        private static string BuildFinalCode(string schemaName, string procedureName, string databaseFullName, string database, GenerationContext context)
        {
            return ProcedureSourceTemplate
                .Replace("{PROCEDURE_SCHEMA}", schemaName)
                .Replace("{PROCEDURE_NAME}", procedureName)
                .Replace("{DATABASE_NAME}", databaseFullName)
                .Replace("{REPOSITORY_NAME}", GetRepositoryFromDatabase(database))
                .Replace("{PARAMETER_PROPERTIES}", context.ParameterProperties.ToString())
                .Replace("{SET_PARAMETER_INTERFACE}", context.SetParameters.ToString())
                .Replace("{HAS_RETURNVAL}", context.HasReturnValue.ToString())
                .Replace("{GET_RETURNVAL_INTERFACE}", context.GetReturnValue.ToString())
                .Replace("{RESULT_CLASS}", context.ResultClass.ToString());
        }

        private class GenerationContext
        {
            public StringBuilder ParameterProperties { get; } = new();
            public StringBuilder SetParameters { get; } = new();
            public StringBuilder GetReturnValue { get; } = new();
            public StringBuilder HasReturnValue { get; } = new();
            public StringBuilder ResultClass { get; } = new();

            public GenerationContext()
            {
                GetReturnValue.Tab(2).AppendLine(@"// Return Value");
                HasReturnValue.Tab(2).AppendLine(@"// Has Return Value");
            }
        }

        private static string GetRepositoryFromDatabase(string database)
        {
            // 데이터베이스 이름에서 Repository 이름을 생성합니다.
            // 예: "MyDatabase" -> "MyDatabaseRepository"
            return $"{database}Repository";
        }
    }
}
