using Generator.Database.Analyzers;
using Generator.Database.Models;
using System.Text;

namespace Generator.Database.Generators
{

    public static class CSharpTableGenerator
    {

        private const string CstTableTemplate = @"// <auto-generated />
// This file was automatically generated. Do not edit manually.

using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace {DATABASE_NAME}.Tables
{
    [Table(""{TABLE_NAME}"")]
    public class {CLASS_NAME}Entity
    {
{PROPERTIES}
    }
}";

        public static GeneratedFile? Generate(string database, TableSchema table)
        {
            var builder = new StringBuilder();
            foreach (var column in table.Columns)
            {
                var property = GeneratePropertyValue(column);
                builder.AppendLine(property);
            }

            var code = CstTableTemplate
                .Replace("{DATABASE_NAME}", database)
                .Replace("{TABLE_NAME}", table.TableName)
                .Replace("{CLASS_NAME}", table.TableName)
                .Replace("{PROPERTIES}", builder.ToString().TrimEnd());

            return new GeneratedFile
            {
                FileName = $"{table.TableName}Entity.cs",
                Content = code,
                CodeType = CodeType.Table,
                Database = database
            };
        }

        private static string GeneratePropertyValue(ColumnSchema column)
        {
            var attributes = new List<string>();

            // Key 속성 추가 (일반적으로 Id 컬럼)
            //if (column.ColumnName.Equals("Id", StringComparison.OrdinalIgnoreCase) ||
            //    column.ColumnName.EndsWith("Id", StringComparison.OrdinalIgnoreCase)) {
            //    attributes.Add("[Key]");
            //}

            // Required 속성 추가
            if (!column.IsNullable)
            {
                attributes.Add("[Required]");
            }

            // StringLength 속성 추가
            if (IsStringType(column.DataType) &&
                column.CharacterMaximumLength.HasValue &&
                column.CharacterMaximumLength.Value > 0)
            {
                attributes.Add($"[StringLength({column.CharacterMaximumLength.Value})]");
            }

            var result = new StringBuilder();
            // Member Value Attributes
            foreach (var attribute in attributes)
            {
                result.Append("\t\t");
                result.AppendLine(attribute);
            }

            {
                // Member Value
                var property = CSharpTypeConverter.GenerateMemberValue(column);
                result.Append("\t\t");
                result.Append(property).AppendLine();
            }

            return result.ToString();
        }

        private static bool IsStringType(string dataType)
        {
            return dataType.ToLower() switch
            {
                "char" or "varchar" or "text" or "nchar" or "nvarchar" or "ntext" => true,
                _ when dataType.StartsWith("varchar") || dataType.StartsWith("nvarchar") => true,
                _ => false
            };
        }
    }
}

