using Generator.Database.Models;
using System.Text;

namespace Generator.Database.Generators
{
    public static class CSharpExtensionGenerator
    {
        private const string ExtensionSourceTemplate = @"// <auto-generated />
// This file was automatically generated. Do not edit manually.

using {DATABASE_NAME}.Tables;
using {DATABASE_NAME}.Procedures;

namespace {DATABASE_NAME}.Extensions
{
    public static class {TABLE_NAME}Extensions {
{EXTENSION_METHODS}
    }
}";

        public static GeneratedFile GenerateForTable(string database, string databaseFullName, string tableName, List<string> procedureNames, List<string>? tableColumns = null)
        {
            var extensionMethods = new StringBuilder();

            foreach (var procedureName in procedureNames)
            {
                GenerateToResultMethod(extensionMethods, tableName, procedureName, tableColumns);
            }

            var generated = ExtensionSourceTemplate
                .Replace("{DATABASE_NAME}", databaseFullName)
                .Replace("{TABLE_NAME}", tableName)
                .Replace("{EXTENSION_METHODS}", extensionMethods.ToString());

            return new GeneratedFile
            {
                FileName = $"{tableName}Extensions.cs",
                Content = generated,
                CodeType = CodeType.Extension,
                Database = databaseFullName
            };
        }

        private static void GenerateToResultMethod(StringBuilder methods, string tableName, string procedureName, List<string>? tableColumns = null)
        {
            // Table → Result 변환
            methods.AppendLine($"        /// <summary>");
            methods.AppendLine($"        /// Converts Table{tableName} to {procedureName}.Result");
            methods.AppendLine($"        /// </summary>");
            methods.AppendLine($"        public static {procedureName}.Result To{procedureName}Result(this Table{tableName} table) {{");
            methods.AppendLine($"            return ({procedureName}.Result)table; // Uses implicit conversion");
            methods.AppendLine($"        }}");
            methods.AppendLine();

            // Result → Table 변환
            methods.AppendLine($"        /// <summary>");
            methods.AppendLine($"        /// Converts {procedureName}.Result to Table{tableName}");
            methods.AppendLine($"        /// </summary>");
            methods.AppendLine($"        public static Table{tableName} ToTable{tableName}(this {procedureName}.Result result) {{");
            methods.AppendLine($"            return (Table{tableName})result; // Uses implicit conversion");
            methods.AppendLine($"        }}");
            methods.AppendLine();
        }
    }
}
