using Generator.Database.Analyzers;
using Generator.Database.Models;
using Generator.Database.Services;
using System.Text;

namespace Generator.Database.Generators
{
    public class YamlTableGenerator
    {
        private readonly MetadataLoader Loader;
        private readonly TablesMetadata? TablesMetadata;
        private readonly MappingsMetadata? MappingsMetadata;

        private const string CstEntityTemplate = @"// <auto-generated />
// This file was automatically generated from YAML metadata. Do not edit manually.

using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace {NAMESPACE};

/// <summary>
/// {DESCRIPTION}
/// </summary>
[Table(""{TABLE_NAME}"", Schema = ""{SCHEMA}"")]
public class {CLASS_NAME}
{
{PROPERTIES}
}";

        public YamlTableGenerator(MetadataLoader loader)
        {
            Loader = loader;
            TablesMetadata = loader.LoadTablesMetadata();
            MappingsMetadata = loader.LoadMappingsMetadata();
        }

        public List<GeneratedFile> GenerateEntities(string database, List<TableSchema> dbTables)
        {
            var generatedFiles = new List<GeneratedFile>();

            if (TablesMetadata == null)
            {
                Console.WriteLine("Warning: No tables metadata loaded, skipping YAML-based generation.");
                return generatedFiles;
            }

            foreach (var tableName in TablesMetadata.Tables.Keys)
            {
                // DB에서 해당 테이블 스키마 찾기
                var tableSchema = dbTables.FirstOrDefault(t =>
                    t.TableName.Equals(tableName, StringComparison.OrdinalIgnoreCase));

                if (tableSchema == null)
                {
                    Console.WriteLine($"Warning: Table '{tableName}' defined in YAML but not found in database.");
                    continue;
                }

                // Entity 생성 여부 확인
                if (!Loader.ShouldGenerateEntity(TablesMetadata, tableName))
                {
                    Console.WriteLine($"Skipped table (Entity generation disabled): {tableName}");
                    continue;
                }

                var generatedFile = GenerateEntity(database, tableSchema, tableName);
                if (generatedFile != null)
                {
                    generatedFiles.Add(generatedFile);
                }
            }

            return generatedFiles;
        }

        private GeneratedFile? GenerateEntity(string database, TableSchema tableSchema, string tableName)
        {
            if (TablesMetadata == null)
            {
                return null;
            }

            var className = Loader.GetEntityClassName(TablesMetadata, tableName);
            if (string.IsNullOrEmpty(className))
            {
                return null;
            }

            var description = TablesMetadata.Tables.TryGetValue(tableName, out var config)
                ? config.Description ?? tableName
                : tableName;

            var excludedColumns = Loader.GetExcludedColumns(TablesMetadata, tableName);
            var schema = TablesMetadata.Defaults?.Schema ?? "dbo";

            var builder = new StringBuilder();
            foreach (var column in tableSchema.Columns)
            {
                // 제외 컬럼 확인
                if (excludedColumns != null && excludedColumns.Contains(column.ColumnName))
                {
                    continue;
                }

                var property = GeneratePropertyValue(column);
                builder.AppendLine(property);
            }

            var code = CstEntityTemplate
                .Replace("{NAMESPACE}", $"{database}.Entities")
                .Replace("{DESCRIPTION}", description)
                .Replace("{TABLE_NAME}", tableName)
                .Replace("{SCHEMA}", schema)
                .Replace("{CLASS_NAME}", className)
                .Replace("{PROPERTIES}", builder.ToString().TrimEnd());

            return new GeneratedFile
            {
                FileName = $"{className}.cs",
                Content = code,
                Database = database
            };
        }

        private static string GeneratePropertyValue(ColumnSchema column)
        {
            var attributes = new List<string>();

            // Required 속성 추가
            if (!column.IsNullable)
            {
                attributes.Add("[Required]");
            }

            // StringLength 속성 추가
            if (IsStringType(column.DataType) &&
                column.CharacterMaximumLength.HasValue &&
                column.CharacterMaximumLength.Value > 0)
            {
                attributes.Add($"[StringLength({column.CharacterMaximumLength.Value})]");
            }

            var result = new StringBuilder();

            // Member Value Attributes
            foreach (var attribute in attributes)
            {
                result.Append("\t");
                result.AppendLine(attribute);
            }

            // Member Value
            var (csharpType, valueType) = CSharpTypeConverter.GetCSharpType(column.DataType, column.UserDefinedType, column.IsNullable);
            var defaultValue = CSharpTypeConverter.GetDefaultValue(valueType, column.IsNullable);
            result.Append("\t");
            result.Append($"public {csharpType} {column.ColumnName} {{ get; set; }} = {defaultValue};");
            result.AppendLine();

            return result.ToString();
        }

        private static bool IsStringType(string dataType)
        {
            return dataType.ToLower() switch
            {
                "char" or "varchar" or "text" or "nchar" or "nvarchar" or "ntext" => true,
                _ when dataType.StartsWith("varchar") || dataType.StartsWith("nvarchar") => true,
                _ => false
            };
        }
    }
}
